apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: k8sapp
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_PORT
        - name: APP_SENDER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: APP_SENDER
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: APP_PASSWORD
